/* Generated by tools/generate_fonts.py from Montserrat (SIL Open Font License 1.1). */
#pragma once

#include "lvgl.h"

extern const lv_font_t bed_font_text_10;
extern const lv_font_t bed_font_text_12;
extern const lv_font_t bed_font_text_14;
extern const lv_font_t bed_font_bold_14;
extern const lv_font_t bed_font_bold_16;
extern const lv_font_t bed_font_bold_20;
extern const lv_font_t bed_font_bold_26;
extern const lv_font_t bed_font_clock_28;
extern const lv_font_t bed_font_clock_34;
extern const lv_font_t bed_font_clock_40;
extern const lv_font_t bed_font_clock_46;
