/* Generated by tools/generate_icons.py from Material Design Icons 7.4.47 (Apache 2.0). */
#pragma once

#include "lvgl.h"

extern const lv_font_t bed_icons_14;
extern const lv_font_t bed_icons_18;
extern const lv_font_t bed_icons_22;

#define BED_ICON_DOOR_OPEN "\xEE\x80\x80" /* mdi:door-open */
#define BED_ICON_SHIELD "\xEE\x80\x81" /* mdi:shield */
#define BED_ICON_SHIELD_OFF "\xEE\x80\x82" /* mdi:shield-off */
#define BED_ICON_SHIELD_HOME "\xEE\x80\x83" /* mdi:shield-home */
#define BED_ICON_SHIELD_LOCK "\xEE\x80\x84" /* mdi:shield-lock */
#define BED_ICON_SHIELD_MOON "\xEE\x80\x85" /* mdi:shield-moon */
#define BED_ICON_SHIELD_AIRPLANE "\xEE\x80\x86" /* mdi:shield-airplane */
#define BED_ICON_SECURITY "\xEE\x80\x87" /* mdi:security */
#define BED_ICON_SHIELD_OUTLINE "\xEE\x80\x88" /* mdi:shield-outline */
#define BED_ICON_BELL_RING "\xEE\x80\x89" /* mdi:bell-ring */
#define BED_ICON_WEATHER_NIGHT "\xEE\x80\x8A" /* mdi:weather-night */
#define BED_ICON_WEATHER_CLOUDY "\xEE\x80\x8B" /* mdi:weather-cloudy */
#define BED_ICON_ALERT_CIRCLE_OUTLINE "\xEE\x80\x8C" /* mdi:alert-circle-outline */
#define BED_ICON_WEATHER_FOG "\xEE\x80\x8D" /* mdi:weather-fog */
#define BED_ICON_WEATHER_HAIL "\xEE\x80\x8E" /* mdi:weather-hail */
#define BED_ICON_WEATHER_LIGHTNING "\xEE\x80\x8F" /* mdi:weather-lightning */
#define BED_ICON_WEATHER_LIGHTNING_RAINY "\xEE\x80\x90" /* mdi:weather-lightning-rainy */
#define BED_ICON_WEATHER_PARTLY_CLOUDY "\xEE\x80\x91" /* mdi:weather-partly-cloudy */
#define BED_ICON_WEATHER_POURING "\xEE\x80\x92" /* mdi:weather-pouring */
#define BED_ICON_WEATHER_RAINY "\xEE\x80\x93" /* mdi:weather-rainy */
#define BED_ICON_WEATHER_SNOWY "\xEE\x80\x94" /* mdi:weather-snowy */
#define BED_ICON_WEATHER_SNOWY_RAINY "\xEE\x80\x95" /* mdi:weather-snowy-rainy */
#define BED_ICON_WEATHER_SUNNY "\xEE\x80\x96" /* mdi:weather-sunny */
#define BED_ICON_WEATHER_WINDY "\xEE\x80\x97" /* mdi:weather-windy */
#define BED_ICON_WEATHER_WINDY_VARIANT "\xEE\x80\x98" /* mdi:weather-windy-variant */
#define BED_ICON_HELP_CIRCLE_OUTLINE "\xEE\x80\x99" /* mdi:help-circle-outline */
